package com.lanou.dllo.mynews.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lanou.dllo.mynews.greendao.Focus;

import com.lanou.dllo.mynews.greendao.FocusDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig focusDaoConfig;

    private final FocusDao focusDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        focusDaoConfig = daoConfigMap.get(FocusDao.class).clone();
        focusDaoConfig.initIdentityScope(type);

        focusDao = new FocusDao(focusDaoConfig, this);

        registerDao(Focus.class, focusDao);
    }
    
    public void clear() {
        focusDaoConfig.getIdentityScope().clear();
    }

    public FocusDao getFocusDao() {
        return focusDao;
    }

}
