package com.lanou.dllo.mynews.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FOCUS".
 */
public class Focus {

    private Long id;
    private String content;
    private String title;
    private String alias;
    private String name;
    private String classification;
    private String picurl;
    private String headpicurl;
    private String expertId;

    public Focus() {
    }

    public Focus(Long id) {
        this.id = id;
    }

    public Focus(Long id, String content, String title, String alias, String name, String classification, String picurl, String headpicurl, String expertId) {
        this.id = id;
        this.content = content;
        this.title = title;
        this.alias = alias;
        this.name = name;
        this.classification = classification;
        this.picurl = picurl;
        this.headpicurl = headpicurl;
        this.expertId = expertId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getClassification() {
        return classification;
    }

    public void setClassification(String classification) {
        this.classification = classification;
    }

    public String getPicurl() {
        return picurl;
    }

    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }

    public String getHeadpicurl() {
        return headpicurl;
    }

    public void setHeadpicurl(String headpicurl) {
        this.headpicurl = headpicurl;
    }

    public String getExpertId() {
        return expertId;
    }

    public void setExpertId(String expertId) {
        this.expertId = expertId;
    }

}
